sequential: true

variables:
  ncpus: [1, 2, 4, 8, 16, 32]
  chunksize: [4, 8, 16, 32, 64, 256, 1024, 4096]
  implname: ["mutex"]

command: "module load CMake/3.29.3-GCCcore-13.3.0 && make clean && CHUNK_SIZE={chunksize} MAX_THREADS={ncpus} make -j2 bin/bfs && mkdir -p targets && mv bin/bfs targets/bfs_{implname}_chunksize{chunksize}_{ncpus}cpus && echo \"Built: targets/bfs_{implname}_chunksize{chunksize}_{ncpus}cpus\" || echo \"Something went wrong\""

jobs:
  - config: "baldo_2cpus"
    config_jobs:
      - tag: "compile"
