sequential: true

variables:
  ncpus: [1] #, 2, 4, 8, 16, 32, 64]
  chunksize: [16] #, 32, 64, 256, 1024, 4096]
  implname: ["atomic"]

command: "module load llvm/EPI-development && make clean && CHUNK_SIZE={chunksize} MAX_THREADS={ncpus} make -j64 bin/bfs CC=clang CXX=clang++ && mkdir -p targets && mv bin/bfs targets/bfs_{implname}_chunksize{chunksize}_{ncpus}cpus && echo \"Built: targets/bfs_{implname}_chunksize{chunksize}_{ncpus}cpus\" || echo \"Something went wrong\""

jobs:
  - config: "pioneer_64cpus"
    config_jobs:
      - tag: "compile"