variables:
  baldo_ncpus: [1, 2, 4, 8, 16, 32]

  chunksize: [16, 32, 64, 256, 1024, 4096]

  mtx:
    - "../datasets/large_diameter/GAP/GAP-road/GAP-road.bmtx"
    - "../datasets/large_diameter/DIMACS10/rgg_n_2_22_s0/rgg_n_2_22_s0.bmtx"
    - "../datasets/large_diameter/DIMACS10/europe_osm/europe_osm.bmtx"
  n: [15]
  implname: ["atomic"]

jobs:
  - config: "baldo_{baldo_ncpus}cpus"
    command: "./targets/bfs_{implname}_chunksize{chunksize}_{baldo_ncpus}cpus -f {mtx} -n {n}"
    config_jobs:
      - tag: "{implname}_chunksize_{chunksize}"