variables:
  ncpus: [1, 2, 4, 8, 16, 32, 64]

  chunksize: [4, 8, 16, 32, 64, 256, 1024, 4096]

  mtx:
    - "../datasets/large_diameter/GAP/GAP-road/GAP-road.bmtx"
    - "../datasets/large_diameter/DIMACS10/rgg_n_2_22_s0/rgg_n_2_22_s0.bmtx"
    - "../datasets/large_diameter/DIMACS10/europe_osm/europe_osm.bmtx"
  n: [20]
  implname: ["mutex"]

jobs:
  - config: "{ncpus}_cpus"
    command: "./targets/bfs_{implname}_chunksize{chunksize}_{ncpus}cpus -f {mtx} -n {n}"
    config_jobs:
      - tag: "{implname}_chunksize_{chunksize}"