# europe_osm read timeouts (walltime: 5min)

variables:
  hpc_ncpus: [1, 2, 4, 8, 16, 24]

  chunksize: [4, 8, 16, 32, 64, 256, 1024, 4096]

  # "datasets/large_diameter/GAP/GAP-road/GAP-road.bmtx"
  # datasets/large_diameter/DIMACS10/rgg_n_2_22_s0/rgg_n_2_22_s0.bmtx
  mtx: ["datasets/large_diameter/DIMACS10/europe_osm/europe_osm.bmtx"] # datasets/large_diameter/matrices_list.txt
  n: [30]
  implname: ["mutex"]

jobs:
  - config: "hpc_{hpc_ncpus}cpus"
    command: "./targets/bfs_{implname}_chunksize{chunksize}_{hpc_ncpus}cpus -f {mtx} -n {n}"
    config_jobs:
      - tag: "{implname}_chunksize_{chunksize}"