variables:
  ncpus: [1, 2, 4, 8, 16, 32]

  chunksize: [4, 8, 16, 32, 64, 256, 1024, 4096]

  mtx: "datasets/matrices_list.txt"
  n: [32]

preprocess: "module load cmake-3.15.4 gcc91"

jobs:
  - config: "baldo_{baldo_ncpus}cpus"
    config_jobs:
      - tag: "pthreads_chunksize{chunksize}_{ncpus}cpus"
        command: "./pthreads/targets/bfs_chunksize{chunksize}_{ncpus}cpus -f {mtx} -n {n}"
      - tag: "openmp_{ncpus}cpus"
        command: "OMP_NUM_THREADS={ncpus} openmp/bin/bfs {mtx} {n} merged_csr_distances"
      - tag: "gapbs_{ncpus}cpus"
        command: "OMP_NUM_THREADS={ncpus} gapbs/bfs -f {mtx} -n {n}"