variables:
  ncpus: [1, 2, 4, 8, 16, 32]

  chunksize: [32, 64, 256, 1024, 4096]

  # mtx: "datasets/asia_osm.mtx"
  n: [32]

preprocess: "module load cmake-3.15.4 gcc91"

jobs:
  - config: "hpc"
    config_jobs:
      - tag: "pthreads_chunksize{chunksize}_{ncpus}cpus"
        command: "./pthreads/targets/bfs_chunksize{chunksize}_{ncpus}cpus -f datasets/GAP-road.mtx -n {n}"
      - tag: "openmp_{ncpus}cpus"
        command: "OMP_NUM_THREADS={ncpus} openmp/bin/bfs datasets/GAP-road.mtx {n} merged_csr_distances"
      - tag: "gapbs_{ncpus}cpus"
        command: "OMP_NUM_THREADS={ncpus} gapbs/bfs -f datasets/GAP-road.mtx -n {n}"