variables:
  pioneer_ncpus: [1, 2, 4, 8, 16, 32, 64]
  bananaf3_ncpus: [1, 2, 4, 8]
  arriesgado_ncpus: [1, 2, 4]

  mtx:
    - "../datasets/large_diameter/GAP/GAP-road/GAP-road.bmtx"
    - "../datasets/large_diameter/DIMACS10/rgg_n_2_22_s0/rgg_n_2_22_s0.bmtx"
    - "../datasets/large_diameter/DIMACS10/europe_osm/europe_osm.bmtx"
  n: [15]
  implname: ["openmp"]

preprocess: "export LD_LIBRARY_PATH=/apps/riscv/llvm/EPI/development/lib"

jobs:
  - config: "pioneer_{pioneer_ncpus}cpus"
    command: "./targets/bfs_{implname} {mtx} {n} merged_csr"
    config_jobs:
      - tag: "{implname}"

  - config: "arriesgado_{arriesgado_ncpus}cpus"
    command: "./targets/bfs_{implname} {mtx} {n} merged_csr"
    config_jobs:
      - tag: "{implname}"

  - config: "bananaf3_{bananaf3_ncpus}cpus"
    command: "./targets/bfs_{implname} {mtx} {n} merged_csr"
    config_jobs:
      - tag: "{implname}"