sequential: true

variables:
  ncpus: [1, 2, 4, 8, 16, 32]
  chunksize: [32, 64, 256, 1024, 4096]
  compile_pthreads: "cd pthreads && mkdir -p targets && make clean"
  compile_openmp: "cd openmp && mkdir -p targets && make clean"
  compile_gapbs: "cd gapbs && make clean"
  postprocess_pthreads: "mv bin/bfs targets/bfs_chunksize{chunksize}_{ncpus}cpus && echo \"Built: targets/bfs_chunksize{chunksize}_{ncpus}cpus\" || echo \"Something went wrong\""
  postprocess_openmp: "mv bin/bfs targets/bfs_frontiers && echo \"Built: bin/bfs\" || echo \"Something went wrong\""
  postprocess_gapbs: "echo \"Built: bfs\" || echo \"Something went wrong\""
  postprocess_openmp_frontiers: "mv bin/bfs targets/bfs_frontiers && echo \"Built: bin/bfs_frontiers\" || echo \"Something went wrong\""

jobs:
  - config: "32_cpus"
    cluster_name: local
    preprocess: "module load cmake-3.15.4 gcc91"
    config_jobs:
      - tag: "compile_pthreads"
        command: "{compile_pthreads} && CHUNK_SIZE={chunksize} MAX_THREADS={ncpus} make -j16 bin/bfs"
        postprocess: "{postprocess_pthreads}"
      - tag: "compile_openmp"
        command: "{compile_openmp} && make -j16 bin/bfs"
        postprocess: "{postprocess_openmp}"
      - tag: "compile_gapbs"
        command: "{compile_gapbs} && make -j16 bfs"
        postprocess: "{postprocess_gapbs}"
      - tag: "compile_frontiers"
        command: "{compile_openmp} && make FRONTIER_DEBUG=1 -j16 bin/bfs"
        postprocess: "{postprocess_openmp_frontiers}"

  - config: "32_cpus"
    cluster_name: hca
    preprocess: "module load llvm/EPI-development && module load cmake/3.28.1"
    config_jobs:
    - tag: "compile_pthreads"
      command: "{compile_pthreads} && CHUNK_SIZE={chunksize} MAX_THREADS={ncpus} CC=clang CXX=clang++ make -j16 bin/bfs"
      postprocess: "{postprocess_pthreads}"
    - tag: "compile_openmp"
      command: "CC=clang CXX=clang++ {compile_openmp} && make -j16 bin/bfs"
      postprocess: "{postprocess_openmp}"
    - tag: "compile_gapbs"
      command: "CC=clang CXX=clang++ {compile_gapbs} && make -j16 bfs"
      postprocess: "{postprocess_gapbs}"
  
  - config: "32_cpus"
    cluster_name: thea
    config_jobs:
    - tag: "compile_pthreads"
      command: "{compile_pthreads} && CHUNK_SIZE={chunksize} MAX_THREADS={ncpus} make -j16 bin/bfs"
      postprocess: "{postprocess_pthreads}"
    - tag: "compile_openmp"
      command: "{compile_openmp} && make -j16 bin/bfs"
      postprocess: "{postprocess_openmp}"
    - tag: "compile_gapbs"
      command: "{compile_gapbs} && make -j16 bfs"
      postprocess: "{postprocess_gapbs}"