variables:
  ncpus: [1, 2, 4, 8, 16, 32]
  chunksize: [4, 8, 16, 32, 64, 256, 1024, 4096]
  mtx: "datasets/large_diameter/matrices_list.txt"
  n: [32]

jobs:
  - config: "96_cpus_papi"
    config_jobs:
      - tag: "gapbs_{ncpus}cpus_papi"
        command: "OMP_NUM_THREADS={ncpus} PAPI_OUTPUT_DIRECTORY=\"papi/gapbs_{ncpus}cpus\" PAPI_EVENTS=\"PAPI_L3_TCA,PAPI_L3_TCM\"" gapbs/targets/bfs_papi -f {mtx} -n {n}"